name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Lint-code:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      
      - name: Install linters
        run: |
          pip install ruff
      
      - name: Run linters & formatters
        run: |
          ruff check --fix --show-fixes .
          ruff format .
  
      - name: Push changes into repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Lint and format'